# Generated by Django 4.1.5 on 2023-01-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Management", "Management"),
                    ("Agent", "Agent"),
                    ("Tenant", "Tenant"),
                ],
                default="Tenant",
                max_length=15,
            ),
        ),
    ]
