# Generated by Django 4.1.5 on 2023-01-19 10:32

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("price", models.PositiveBigIntegerField()),
                ("details", models.TextField()),
                ("listed_on", models.DateTimeField(auto_now_add=True)),
                ("similar_units", models.PositiveIntegerField(default=1)),
                ("amenities", models.TextField()),
                ("available_units", models.PositiveIntegerField(default=1)),
                (
                    "ownership",
                    models.CharField(
                        choices=[("Sale", "Sale"), ("Rent", "Rent")],
                        default="Rent",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("One Bedroom", "One Bedroom"),
                            ("Two Bedroom", "Two Bedroom"),
                            ("Three Bedroom", "Three Bedroom"),
                            ("Studio", "Studio"),
                        ],
                        default="Studio",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Estate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "unique_together": {("county", "name")},
            },
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("price", models.PositiveBigIntegerField()),
                ("details", models.TextField()),
                ("listed_on", models.DateTimeField(auto_now_add=True)),
                ("similar_units", models.PositiveIntegerField(default=1)),
                ("amenities", models.TextField()),
                ("available_units", models.PositiveIntegerField(default=1)),
                (
                    "ownership",
                    models.CharField(
                        choices=[("Sale", "Sale"), ("Rent", "Rent")],
                        default="Rent",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Two Bedroom", "Two Bedroom"),
                            ("Three Bedroom", "Three Bedroom"),
                            ("Four Bedroom", "Four Bedroom"),
                            ("Five Bedroom", "Five Bedroom"),
                        ],
                        default="Two Bedroom",
                        max_length=50,
                    ),
                ),
                ("bathrooms", models.PositiveIntegerField(default=1)),
                ("village", models.CharField(max_length=100)),
                (
                    "estate",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estate_%(class)s",
                        to="property.estate",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="my_%(class)s_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_%(class)s_listing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(upload_to="property"),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartement_images",
                        to="property.apartment",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house_images",
                        to="property.house",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="apartment",
            name="estate",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estate_%(class)s",
                to="property.estate",
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="my_%(class)s_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="listed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_%(class)s_listing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
