# Generated by Django 4.1.5 on 2023-01-13 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="likes",
            field=models.ManyToManyField(
                null=True,
                related_name="my_%(class)s_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="likes",
            field=models.ManyToManyField(
                null=True,
                related_name="my_%(class)s_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
