# Generated by Django 4.1.5 on 2023-01-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_alter_estate_county"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estate",
            name="county",
            field=models.CharField(max_length=100),
        ),
    ]
