# Generated by Django 4.1.5 on 2023-01-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_alter_apartment_amenities_alter_apartment_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="amenities",
            field=models.JSONField(
                default={
                    "id": 30695833,
                    "lat": -1.3164518,
                    "lon": 36.8348783,
                    "tags": {
                        "addr:city": "Nairobi",
                        "addr:street": "Mombasa Road",
                        "name": "Naivas Supermarket",
                        "shop": "supermarket",
                    },
                    "type": "node",
                }
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="details",
            field=models.JSONField(
                default={
                    "id": 30695833,
                    "lat": -1.3164518,
                    "lon": 36.8348783,
                    "tags": {
                        "addr:city": "Nairobi",
                        "addr:street": "Mombasa Road",
                        "name": "Naivas Supermarket",
                        "shop": "supermarket",
                    },
                    "type": "node",
                }
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="amenities",
            field=models.JSONField(
                default={
                    "id": 30695833,
                    "lat": -1.3164518,
                    "lon": 36.8348783,
                    "tags": {
                        "addr:city": "Nairobi",
                        "addr:street": "Mombasa Road",
                        "name": "Naivas Supermarket",
                        "shop": "supermarket",
                    },
                    "type": "node",
                }
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="details",
            field=models.JSONField(
                default={
                    "id": 30695833,
                    "lat": -1.3164518,
                    "lon": 36.8348783,
                    "tags": {
                        "addr:city": "Nairobi",
                        "addr:street": "Mombasa Road",
                        "name": "Naivas Supermarket",
                        "shop": "supermarket",
                    },
                    "type": "node",
                }
            ),
        ),
    ]
