# Generated by Django 4.1.5 on 2023-01-19 14:48

from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0005_alter_apartment_amenities_alter_apartment_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="amenities",
            field=models.JSONField(default=property.models.default_json),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="details",
            field=models.JSONField(default=property.models.default_json),
        ),
        migrations.AlterField(
            model_name="house",
            name="amenities",
            field=models.JSONField(default=property.models.default_json),
        ),
        migrations.AlterField(
            model_name="house",
            name="details",
            field=models.JSONField(default=property.models.default_json),
        ),
    ]
