# Generated by Django 4.1.5 on 2023-01-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0006_alter_apartment_amenities_alter_apartment_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="estate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estate_%(class)s",
                to="property.estate",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="estate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estate_%(class)s",
                to="property.estate",
            ),
        ),
    ]
