# Generated by Django 4.1.5 on 2023-01-20 11:57

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0007_alter_apartment_estate_alter_house_estate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                upload_to="media/property"
            ),
        ),
    ]
