# Generated by Django 4.1.5 on 2023-01-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0008_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="media/property"),
        ),
    ]
