# Generated by Django 4.1.5 on 2023-01-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0009_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="estate",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
