# Generated by Django 4.1.5 on 2023-01-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0010_estate_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estate",
            old_name="county",
            new_name="region",
        ),
        migrations.AlterUniqueTogether(
            name="estate",
            unique_together={("region", "name")},
        ),
    ]
